version: "3.9"
services:
  web:
    build: .
    container_name: noteshub-web
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge 