version: "3.9"
services:
  web:
    build: .
    container_name: noteshub-web
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge 